#!/bin/bash
echo drop database onlineshop\;|mysql -u root --password=12345678
echo create database onlineshop\;|mysql -u root --password=12345678
mysql -u root --password=12345678 onlineshop <waren
mysql -u root --password=12345678 onlineshop <bezahlungen
mysql -u root --password=12345678 onlineshop <verkaeufe
mysql -u root --password=12345678 onlineshop <warenkorb
